Repository sablier-labs/v2-docs, pull requests merged in 2023-07, with the labels that each got.

#32 refactor: restyle
  .github/workflows/cd.yml
  .prettierrc.yml
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
  src/components/FunctionPlot.tsx
  src/components/HomepageFeatures.module.css
  src/components/HomepageFeatures.tsx
  src/components/HomepageHeader.module.css
  src/components/HomepageHeader.tsx
  src/components/LinkPreview.tsx
  src/components/atoms/Background/index.tsx
  src/components/molecules/Feature/index.tsx
  src/components/organisms/Header/Underlay/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Socials/index.tsx
  src/css/custom.css
  src/css/sablier.css
  src/pages/index.tsx
  static/decor/grid-pattern.svg
  static/decor/noise-dark100.svg
  tsconfig.json
Labels: enhancement, feature

#42 fix: fix hyperlinks in reference
  docs/contracts/v2/reference/core/abstracts/abstract.Adminable.md
  docs/contracts/v2/reference/core/abstracts/abstract.SablierV2Base.md
  docs/contracts/v2/reference/core/abstracts/abstract.SablierV2Lockup.md
  docs/contracts/v2/reference/core/contract.SablierV2Comptroller.md
  docs/contracts/v2/reference/core/contract.SablierV2LockupDynamic.md
  docs/contracts/v2/reference/core/contract.SablierV2LockupLinear.md
  docs/contracts/v2/reference/core/contract.SablierV2NFTDescriptor.md
  docs/contracts/v2/reference/periphery/contract.SablierV2Archive.md
  docs/contracts/v2/reference/periphery/contract.SablierV2ProxyPlugin.md
  docs/contracts/v2/reference/periphery/contract.SablierV2ProxyTarget.md
  scripts/autogen.sh
Labels: bug

#45 build: bump node.js deps
  package.json
  pnpm-lock.yaml
Labels: dependencies

#39 refactor: remove "index.tsx" files
  docusaurus.config.js
  src/components/atoms/Background.tsx
  src/components/molecules/Feature.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/Header/Underlay.tsx
  src/components/organisms/Socials.tsx
  src/css/custom.css
  src/css/sablier.css
Labels: enhancement

#47 feat: prop up deployments and governance
  docs/concepts/05-governance.md
  docs/concepts/06-glossary.md
  docs/contracts/v1/guides/deployments.md
  docs/contracts/v2/02-deployments.md
  docs/contracts/v2/guides/create-stream/01-lockup-linear.mdx
  docs/contracts/v2/guides/create-stream/02-lockup-dynamic.mdx
  docs/contracts/v2/guides/stream-management/01-setup.md
  docusaurus.config.js
Labels: enhancement, feature

#48 refactor: update errors page
  docs/contracts/v2/02-deployments.md
  docs/contracts/v2/reference/05-errors.md
Labels: enhancement

#49 refactor: update statuses page
  docs/concepts/protocol/02-stream-types.mdx
  docs/concepts/protocol/05-statuses.md
Labels: enhancement, feature

#52 docs: reference overview
  docs/contracts/v2/guides/stream-management/03-cancel.md
  docs/contracts/v2/reference/01-overview.md
Labels: enhancement, feature

#53 refactor: disable flash loan pages
  docs/concepts/02-sablier-protocol.md
  docs/concepts/05-governance.md
  docs/concepts/06-glossary.md
  docs/concepts/protocol/06-fees.mdx
  docs/concepts/protocol/07-flash-loans.mdx
  docs/contracts/v2/guides/05-flash-loans.md
Labels: enhancement

#57 feat: reference diagrams
  docs/contracts/v2/reference/02-diagrams.md
  docs/contracts/v2/reference/05-access-control.md
  docs/contracts/v2/reference/06-errors.md
  docs/contracts/v2/reference/core/_category_.json
  docs/contracts/v2/reference/periphery/_category_.json
Labels: feature

#62 feat: add Lockup Linear and Lockup Dynamic diagrams
  docs/contracts/v2/reference/02-diagrams.md
Labels: feature

#67 Improve diagrams
  docs/contracts/v2/reference/02-diagrams.md
Labels: enhancement

#74 fix: fix integration template url
  docs/contracts/v2/guides/01-local-environment.md
Labels: bug
